### ISSUE TITLE
Shows light on dark mode

### ISSUE THREAD

**Issue by broccoder** [ThePotatoChronicler/ThePotatoChronicler#1]
![image](https://user-images.githubusercontent.com/59830101/207632844-f41dc821-dd05-4505-93ce-e7b0707fb85a.png)

^ Terrible light mode ^
Please use this: https://github.com/anuraghazra/github-readme-stats#use-githubs-theme-context-tag

**Comment by ThePotatoChronicler** [comment]
Thanks, fixed in https://github.com/ThePotatoChronicler/ThePotatoChronicler/commit/6c9b2d0d82e97fe193454d8224b5805c99ef22a9
